<ul data-view-id="main_navigation" style="z-index:2" class="Navigation__Wrapper-knnw0g-0 jJSxyD">
            <li data-view-id="main_navigation_item" class="MenuItem-sc-181aa19-0 cOJYFK">
                <a href="https://tiki.vn/dien-thoai-may-tinh-bang/c1789?src=c.1789.hamburger_menu_fly_out_banner" rel="" class="MenuItem__MenuLink-sc-181aa19-1 bDtEiz"><span class="icon-wrap"><i class="icon-main-menu-cellphone lv1-icon tikicon"></i></span><span class="text abc">Điện Thoại - Máy Tính Bảng</span></a>
                <div class="SubMenu__NavSub-ykxlng-0 bgEYwg header-sub-menu">
                    <ul>
                          <li class="SubMenu__NavSubCol-ykxlng-2 jiKhdj"><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 dWoJRG"><a href="https://tiki.vn/thuc-pham/c15074?src=c.15074.hamburger_menu_fly_out_banner" rel="nofollow">XU HƯỚNG</a></span><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 iethhs"><a href="https://tiki.vn/dau-an/c5477?src=c.5477.hamburger_menu_fly_out_banner" rel="nofollow">Iphone 11</a></span><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 iethhs"><a href="https://tiki.vn/do-hop/c4419?src=c.4419.hamburger_menu_fly_out_banner" rel="nofollow">Samsung Galaxy S20 Plus</a></span><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 iethhs"><a href="https://tiki.vn/gia-vi/c4422?src=c.4422.hamburger_menu_fly_out_banner" rel="nofollow">Samsung Galaxy A51</a></span><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 iethhs"><a href="https://tiki.vn/thuc-pham-an-lien/c4420?src=c.4420.hamburger_menu_fly_out_banner" rel="nofollow">Samsung Galaxy M11</a></span><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 iethhs"><a href="https://tiki.vn/thuc-pham-chay/c5479?src=c.5479.hamburger_menu_fly_out_banner" rel="nofollow">Samsung Galaxy A31</a></span><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 iethhs"><a href="https://tiki.vn/nau-an-va-lam-banh/c11256?src=c.11256.hamburger_menu_fly_out_banner" rel="nofollow">Nấu ăn &amp; Làm bánh</a></span><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 iethhs"><a href="https://tiki.vn/thuc-pham-kho/c4393?src=c.4393.hamburger_menu_fly_out_banner" rel="nofollow">Ipad Mini 5</a></span><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 iethhs"><a href="https://tiki.vn/bach-hoa-online/c4384?src=c.4384.hamburger_menu_fly_out_banner" rel="nofollow">Ipad 10.2</a></span><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 iethhs"><a href="https://tiki.vn/keo/c8276?src=c.8276.hamburger_menu_fly_out_banner" rel="nofollow">Samsung Galaxy A20s</a></span><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 iethhs"><a href="https://tiki.vn/chocolate/c8277?src=c.8277.hamburger_menu_fly_out_banner" rel="nofollow">Iphone 11 Pro Max 64GB</a></span></li>
                          <li class="SubMenu__NavSubCol-ykxlng-2 jiKhdj"><a href="https://tiki.vn/chuong-trinh/bach-hoa-online?src=c.4384.megamenuflyoutbanner" class="SingleBanner__Root-sc-17nzi45-0 jnXfSj"><img src="https://salt.tikicdn.com/ts/banner/5a/3b/b7/3e39ad10a9cd3daec79a2acedc7b546c.jpg"></a></li>
                        
                     
                    </ul>
                </div>
            </li>
            <li data-view-id="main_navigation_item" class="MenuItem-sc-181aa19-0 cOJYFK">
                <a href="https://tiki.vn/tivi-thiet-bi-nghe-nhin/c4221?src=c.4221.hamburger_menu_fly_out_banner" rel="" class="MenuItem__MenuLink-sc-181aa19-1 bDtEiz"><span class="icon-wrap"><i class="icon-main-menu-tv lv1-icon tikicon"></i></span><span class="text abc">Điện Tử - Điện Lạnh</span></a>
                <div class="SubMenu__NavSub-ykxlng-0 bgEYwg header-sub-menu">
                    <ul>
                                      <li class="SubMenu__NavSubCol-ykxlng-2 jiKhdj"><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 dWoJRG"><a href="https://tiki.vn/thuc-pham/c15074?src=c.15074.hamburger_menu_fly_out_banner" rel="nofollow">TIVI</a></span><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 iethhs"><a href="https://tiki.vn/dau-an/c5477?src=c.5477.hamburger_menu_fly_out_banner" rel="nofollow">Tivi mới </a></span><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 iethhs"><a href="https://tiki.vn/do-hop/c4419?src=c.4419.hamburger_menu_fly_out_banner" rel="nofollow">Tivi bán chạy</a></span><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 iethhs"><a href="https://tiki.vn/gia-vi/c4422?src=c.4422.hamburger_menu_fly_out_banner" rel="nofollow">Smart TV</a></span><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 iethhs"><a href="https://tiki.vn/thuc-pham-an-lien/c4420?src=c.4420.hamburger_menu_fly_out_banner" rel="nofollow">Tivi Cao cấp</a></span><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 iethhs"><a href="https://tiki.vn/thuc-pham-chay/c5479?src=c.5479.hamburger_menu_fly_out_banner" rel="nofollow">Tivi 4k</a></span><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 iethhs"><a href="https://tiki.vn/nau-an-va-lam-banh/c11256?src=c.11256.hamburger_menu_fly_out_banner" rel="nofollow">Nấu ăn &amp; Làm bánh</a></span><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 iethhs"><a href="https://tiki.vn/thuc-pham-kho/c4393?src=c.4393.hamburger_menu_fly_out_banner" rel="nofollow">Tivi LED thường</a></span><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 iethhs"><a href="https://tiki.vn/bach-hoa-online/c4384?src=c.4384.hamburger_menu_fly_out_banner" rel="nofollow">Tivi QLED</a></span><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 iethhs"><a href="https://tiki.vn/keo/c8276?src=c.8276.hamburger_menu_fly_out_banner" rel="nofollow">TIVI QLED</a></span><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 iethhs"><a href="https://tiki.vn/chocolate/c8277?src=c.8277.hamburger_menu_fly_out_banner" rel="nofollow">Internet TV</a></span></li>   
                                      <li class="SubMenu__NavSubCol-ykxlng-2 jiKhdj"><a href="https://tiki.vn/chuong-trinh/bach-hoa-online?src=c.4384.megamenuflyoutbanner" class="SingleBanner__Root-sc-17nzi45-0 jnXfSj"><img src="https://salt.tikicdn.com/ts/banner/5a/3b/b7/3e39ad10a9cd3daec79a2acedc7b546c.jpg"></a></li>
                    </ul>
                </div>
            </li>
            <li data-view-id="main_navigation_item" class="MenuItem-sc-181aa19-0 cOJYFK">
                <a href="https://tiki.vn/thiet-bi-kts-phu-kien-so/c1815?src=c.1815.hamburger_menu_fly_out_banner" rel="" class="MenuItem__MenuLink-sc-181aa19-1 bDtEiz"><span class="icon-wrap"><i class="icon-main-menu-headphone lv1-icon tikicon"></i></span><span class="text abc">Phụ Kiện - Thiết Bị Số</span></a>
                <div class="SubMenu__NavSub-ykxlng-0 bgEYwg header-sub-menu">
                    <ul>
                         <li class="SubMenu__NavSubCol-ykxlng-2 jiKhdj"><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 dWoJRG"><a href="https://tiki.vn/thuc-pham/c15074?src=c.15074.hamburger_menu_fly_out_banner" rel="nofollow">Tai Nghe</a></span><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 iethhs"><a href="https://tiki.vn/dau-an/c5477?src=c.5477.hamburger_menu_fly_out_banner" rel="nofollow">Tai nghe nhét tai</a></span><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 iethhs"><a href="https://tiki.vn/do-hop/c4419?src=c.4419.hamburger_menu_fly_out_banner" rel="nofollow">Tai nghe chụp tai</a></span><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 iethhs"><a href="https://tiki.vn/gia-vi/c4422?src=c.4422.hamburger_menu_fly_out_banner" rel="nofollow">Tai nghe Bluetooth</a></span><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 dWoJRG"><a href="https://tiki.vn/thuc-pham/c15074?src=c.15074.hamburger_menu_fly_out_banner" rel="nofollow">Loa</a></span><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 iethhs"><a href="https://tiki.vn/thuc-pham-an-lien/c4420?src=c.4420.hamburger_menu_fly_out_banner" rel="nofollow">Loa vi tính</a></span><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 iethhs"><a href="https://tiki.vn/thuc-pham-chay/c5479?src=c.5479.hamburger_menu_fly_out_banner" rel="nofollow">Loa bluetooth</a></span><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 iethhs"><a href="https://tiki.vn/nau-an-va-lam-banh/c11256?src=c.11256.hamburger_menu_fly_out_banner" rel="nofollow">Nấu ăn &amp; Làm bánh</a></span><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 iethhs"><a href="https://tiki.vn/thuc-pham-kho/c4393?src=c.4393.hamburger_menu_fly_out_banner" rel="nofollow">Loa kéo</a></span></li>
                         <li class="SubMenu__NavSubCol-ykxlng-2 jiKhdj"><a href="https://tiki.vn/chuong-trinh/bach-hoa-online?src=c.4384.megamenuflyoutbanner" class="SingleBanner__Root-sc-17nzi45-0 jnXfSj"><img src="https://salt.tikicdn.com/ts/banner/5a/3b/b7/3e39ad10a9cd3daec79a2acedc7b546c.jpg"></a></li>
                    
                    </ul>
                </div>
            </li>
            <li data-view-id="main_navigation_item" class="MenuItem-sc-181aa19-0 cOJYFK">
                <a href="https://tiki.vn/laptop-may-vi-tinh/c1846?src=c.1846.hamburger_menu_fly_out_banner" rel="" class="MenuItem__MenuLink-sc-181aa19-1 bDtEiz"><span class="icon-wrap"><i class="icon-main-menu-laptop lv1-icon tikicon"></i></span><span class="text abc">Laptop - Thiết bị IT</span></a>
                <div class="SubMenu__NavSub-ykxlng-0 bgEYwg header-sub-menu">
                    <ul>
                            <li class="SubMenu__NavSubCol-ykxlng-2 jiKhdj"><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 dWoJRG"><a href="https://tiki.vn/thuc-pham/c15074?src=c.15074.hamburger_menu_fly_out_banner" rel="nofollow">Laptop theo giá</a></span><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 iethhs"><a href="https://tiki.vn/dau-an/c5477?src=c.5477.hamburger_menu_fly_out_banner" rel="nofollow">Dưới 8 triệu</a></span><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 iethhs"><a href="https://tiki.vn/do-hop/c4419?src=c.4419.hamburger_menu_fly_out_banner" rel="nofollow">Từ 8-10 Triệu</a></span><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 iethhs"><a href="https://tiki.vn/gia-vi/c4422?src=c.4422.hamburger_menu_fly_out_banner" rel="nofollow">Trên 10 triệu</a></span><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 dWoJRG"><a href="https://tiki.vn/thuc-pham/c15074?src=c.15074.hamburger_menu_fly_out_banner" rel="nofollow">Laptop chính hãng</a></span><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 iethhs"><a href="https://tiki.vn/thuc-pham-an-lien/c4420?src=c.4420.hamburger_menu_fly_out_banner" rel="nofollow">Macbook</a></span><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 iethhs"><a href="https://tiki.vn/thuc-pham-chay/c5479?src=c.5479.hamburger_menu_fly_out_banner" rel="nofollow">Dell</a></span><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 iethhs"><a href="https://tiki.vn/nau-an-va-lam-banh/c11256?src=c.11256.hamburger_menu_fly_out_banner" rel="nofollow">Nấu ăn &amp; Làm bánh</a></span><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 iethhs"><a href="https://tiki.vn/thuc-pham-kho/c4393?src=c.4393.hamburger_menu_fly_out_banner" rel="nofollow">Asus</a></span></li>
                            <li class="SubMenu__NavSubCol-ykxlng-2 jiKhdj"><a href="https://tiki.vn/chuong-trinh/bach-hoa-online?src=c.4384.megamenuflyoutbanner" class="SingleBanner__Root-sc-17nzi45-0 jnXfSj"><img src="https://salt.tikicdn.com/ts/banner/5a/3b/b7/3e39ad10a9cd3daec79a2acedc7b546c.jpg"></a></li>
                       
                    </ul>
                </div>
            </li>
            <li data-view-id="main_navigation_item" class="MenuItem-sc-181aa19-0 cOJYFK">
                <a href="https://tiki.vn/may-anh/c1801?src=c.1801.hamburger_menu_fly_out_banner" rel="" class="MenuItem__MenuLink-sc-181aa19-1 bDtEiz"><span class="icon-wrap"><i class="icon-main-menu-camera lv1-icon tikicon"></i></span><span class="text abc">Máy Ảnh - Quay Phim</span></a>
                <div class="SubMenu__NavSub-ykxlng-0 bgEYwg header-sub-menu">
                    <ul>
                          <li class="SubMenu__NavSubCol-ykxlng-2 jiKhdj"><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 dWoJRG"><a href="https://tiki.vn/thuc-pham/c15074?src=c.15074.hamburger_menu_fly_out_banner" rel="nofollow">Sản phẩm nổi bật</a></span><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 iethhs"><a href="https://tiki.vn/dau-an/c5477?src=c.5477.hamburger_menu_fly_out_banner" rel="nofollow">Canon 750D + Lens 18-55 IS STM</a></span><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 iethhs"><a href="https://tiki.vn/do-hop/c4419?src=c.4419.hamburger_menu_fly_out_banner" rel="nofollow">Canon M10 kit 15-45mm</a></span><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 iethhs"><a href="https://tiki.vn/gia-vi/c4422?src=c.4422.hamburger_menu_fly_out_banner" rel="nofollow">Sony Alpha A600</a></span><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 dWoJRG"><a href="https://tiki.vn/thuc-pham/c15074?src=c.15074.hamburger_menu_fly_out_banner" rel="nofollow">Ống kính - lens</a></span><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 iethhs"><a href="https://tiki.vn/thuc-pham-an-lien/c4420?src=c.4420.hamburger_menu_fly_out_banner" rel="nofollow">Lens Canon</a></span><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 iethhs"><a href="https://tiki.vn/thuc-pham-chay/c5479?src=c.5479.hamburger_menu_fly_out_banner" rel="nofollow">Lens Sony</a></span><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 iethhs"><a href="https://tiki.vn/nau-an-va-lam-banh/c11256?src=c.11256.hamburger_menu_fly_out_banner" rel="nofollow">Lens Sigma</a></span><span data-view-id="main_navigation_sub_item" class="SubMenu__NavSubItem-ykxlng-1 iethhs"><a href="https://tiki.vn/thuc-pham-kho/c4393?src=c.4393.hamburger_menu_fly_out_banner" rel="nofollow">Lens Nikon</a></span></li>
                          <li class="SubMenu__NavSubCol-ykxlng-2 jiKhdj"><a href="https://tiki.vn/chuong-trinh/bach-hoa-online?src=c.4384.megamenuflyoutbanner" class="SingleBanner__Root-sc-17nzi45-0 jnXfSj"><img src="https://salt.tikicdn.com/ts/banner/5a/3b/b7/3e39ad10a9cd3daec79a2acedc7b546c.jpg"></a></li>
                     
                    </ul>
                </div>
            </li>
               <li data-view-id="main_navigation_item" class="MenuItem-sc-181aa19-0 cOJYFK">
                <a href="http://localhost:88/LBM/category/tin-tuc/" rel="" class="MenuItem__MenuLink-sc-181aa19-1 bDtEiz"><span class="icon-wrap"><i class="icon-main-menu-global lv1-icon tikicon"></i></span><span class="text abc">Tin Tức</span></a>   
             
            </li>
        </ul>
        